[2025-04-08T06:06:56.296+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-08T06:06:56.299+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-08T06:06:56.299+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-08T06:06:56.304+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_processed_comments> on 2025-04-08 00:00:00+00:00
[2025-04-08T06:06:56.311+0000] {standard_task_runner.py:60} INFO - Started process 9558 to run task
[2025-04-08T06:06:56.316+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_comment_analysis_pipeline', 'save_processed_comments', 'manual__2025-04-08T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/Sentiment_Topicmodelling.py', '--cfg-path', '/tmp/tmpq8x5xu7n']
[2025-04-08T06:06:56.321+0000] {standard_task_runner.py:88} INFO - Job 172: Subtask save_processed_comments
[2025-04-08T06:06:56.355+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-08T00:00:00+00:00 [running]> on host 288775c8919d
[2025-04-08T06:06:56.396+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_comment_analysis_pipeline' AIRFLOW_CTX_TASK_ID='save_processed_comments' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T00:00:00+00:00'
[2025-04-08T06:06:56.471+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-08T06:07:06.393+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to upstream_failed. Terminating instance.
[2025-04-08T06:07:06.396+0000] {process_utils.py:131} INFO - Sending 15 to group 9558. PIDs of all processes in the group: [9558]
[2025-04-08T06:07:06.396+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 9558
[2025-04-08T06:07:06.595+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-08T06:07:06.664+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9558, status='terminated', exitcode=0, started='06:06:55') (9558) terminated with exit code 0
