[2025-04-13T00:42:16.877+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-13T00:42:16.879+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-13T00:42:16.879+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 5
[2025-04-13T00:42:16.884+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_bertopic> on 2025-04-06 00:00:00+00:00
[2025-04-13T00:42:16.888+0000] {standard_task_runner.py:60} INFO - Started process 33304 to run task
[2025-04-13T00:42:16.890+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_comment_analysis_pipeline', 'run_bertopic', 'manual__2025-04-06T00:00:00+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/Sentiment_Topicmodelling.py', '--cfg-path', '/tmp/tmp86zbb663']
[2025-04-13T00:42:16.891+0000] {standard_task_runner.py:88} INFO - Job 295: Subtask run_bertopic
[2025-04-13T00:42:16.912+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [running]> on host 61c0c751e7f9
[2025-04-13T00:42:16.941+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_comment_analysis_pipeline' AIRFLOW_CTX_TASK_ID='run_bertopic' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T00:00:00+00:00'
[2025-04-13T00:42:16.973+0000] {logging_mixin.py:188} INFO - comments 14406 over 10000 sampling to 10000
[2025-04-13T00:42:16.973+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Sentiment_Topicmodelling.py", line 87, in run_bertopic
    comments = random.sample(comments, 10000)
NameError: name 'random' is not defined
[2025-04-13T00:42:16.977+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=weekly_comment_analysis_pipeline, task_id=run_bertopic, execution_date=20250406T000000, start_date=20250413T004216, end_date=20250413T004216
[2025-04-13T00:42:16.981+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 295 for task run_bertopic (name 'random' is not defined; 33304)
[2025-04-13T00:42:16.990+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-13T00:42:16.999+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
