[2025-04-12T13:22:55.013+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-12T13:22:55.043+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-12T13:22:55.044+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-12T13:22:55.070+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_processed_comments> on 2025-04-06 00:00:00+00:00
[2025-04-12T13:22:55.106+0000] {standard_task_runner.py:60} INFO - Started process 54290 to run task
[2025-04-12T13:22:55.116+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_comment_analysis_pipeline', 'save_processed_comments', 'manual__2025-04-06T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/Sentiment_Topicmodelling.py', '--cfg-path', '/tmp/tmpbhmsyhtw']
[2025-04-12T13:22:55.123+0000] {standard_task_runner.py:88} INFO - Job 231: Subtask save_processed_comments
[2025-04-12T13:22:55.282+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-06T00:00:00+00:00 [running]> on host 09c1abf4dbfb
[2025-04-12T13:22:55.422+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_comment_analysis_pipeline' AIRFLOW_CTX_TASK_ID='save_processed_comments' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T00:00:00+00:00'
[2025-04-12T13:22:55.476+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-12T13:22:57.876+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Sentiment_Topicmodelling.py", line 98, in save_processed_comments
    values = [
TypeError: 'NoneType' object is not iterable
[2025-04-12T13:22:57.888+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=weekly_comment_analysis_pipeline, task_id=save_processed_comments, execution_date=20250406T000000, start_date=20250412T132255, end_date=20250412T132257
[2025-04-12T13:22:57.902+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 231 for task save_processed_comments ('NoneType' object is not iterable; 54290)
[2025-04-12T13:22:57.965+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-12T13:22:57.983+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T00:53:36.099+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-13T00:53:36.103+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-13T00:53:36.103+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-13T00:53:36.107+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_processed_comments> on 2025-04-06 00:00:00+00:00
[2025-04-13T00:53:36.114+0000] {standard_task_runner.py:60} INFO - Started process 63975 to run task
[2025-04-13T00:53:36.117+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_comment_analysis_pipeline', 'save_processed_comments', 'manual__2025-04-06T00:00:00+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/Sentiment_Topicmodelling.py', '--cfg-path', '/tmp/tmpgaxci47h']
[2025-04-13T00:53:36.119+0000] {standard_task_runner.py:88} INFO - Job 297: Subtask save_processed_comments
[2025-04-13T00:53:36.143+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-06T00:00:00+00:00 [running]> on host 61c0c751e7f9
[2025-04-13T00:53:36.175+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_comment_analysis_pipeline' AIRFLOW_CTX_TASK_ID='save_processed_comments' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T00:00:00+00:00'
[2025-04-13T00:53:36.241+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-13T00:54:08.674+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-13T00:54:08.686+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weekly_comment_analysis_pipeline, task_id=save_processed_comments, execution_date=20250406T000000, start_date=20250413T005336, end_date=20250413T005408
[2025-04-13T00:54:08.738+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-13T00:54:08.751+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
